In [84]:
import pandas as pd

# 1. Carregue os conjuntos de dados de gasolina em dois DataFames diferentes e combine-os em um único DataFrame

In [14]:
gasolina_2000 = pd.read_csv("gasolina_2000+.csv", index_col = 0)
gasolina_2010 = pd.read_csv("gasolina_2010+.csv", low_memory = False, index_col = 0)

In [15]:
gasolina_2010

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
9256,2011-01-02,2011-01-08,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,2.030,0.003,2.020,2.050,0.411,0.001,1.619,0.013,1.6111,1.6411,0.008
9257,2011-01-02,2011-01-08,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.717,0.102,1.490,1.990,0.225,0.059,1.492,0.069,1.3221,1.6201,0.046
9258,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,141,R$/l,1.848,0.148,1.590,2.490,0.326,0.080,1.522,0.105,1.2833,1.7486,0.069
9259,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,132,R$/l,1.893,0.108,1.699,2.199,0.191,0.057,1.702,0.04,1.5915,1.79,0.024
9260,2011-01-02,2011-01-08,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,2.026,0.084,1.749,2.100,0.268,0.041,1.758,0.042,1.63,1.848,0.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [16]:
print(gasolina_2000.columns)

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='object')

In [17]:
print(gasolina_2010.columns)

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='object')

In [19]:
juntos = [gasolina_2000, gasolina_2010]
df_gasolina_2000_2010 = pd.concat(juntos)

# 2. Investigue as colunas e entenda o conjunto de dados

In [21]:
df_gasolina_2000_2010

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [22]:
df_gasolina_2000_2010.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [23]:
df_gasolina_2000_2010.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,COEF DE VARIAÇÃO REVENDA
count,120823.000000,120823.000000,120823.000000,120823.000000,120823.000000,120823.000000
mean,221.066461,11.473440,0.684132,9.977821,13.233902,0.045298
std,387.940239,19.161823,1.403317,16.433783,22.451445,0.024763
min,1.000000,0.766000,0.000000,0.590000,0.999000,0.000000
25%,39.000000,2.157000,0.075000,1.989000,2.420000,0.029000
50%,99.000000,2.899000,0.121000,2.690000,3.200000,0.041000
75%,226.000000,4.026000,0.204000,3.790000,4.589000,0.058000
max,4167.000000,107.500000,10.748000,100.000000,120.000000,0.395000

In [24]:
df_gasolina_2000_2010.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 17.5+ MB

# 3. Selecione a terceira coluna da coluna DATA INICIAL e verifique seu tipo

In [41]:
valor = df_gasolina_2000_2010['data inicial'.upper()][2]

In [42]:
type(valor)

str

# 4. Converta as colunas DATA INCIAL E DATA FINAL PARA TIMESTAMP

In [43]:
df_backup = df_gasolina_2000_2010.copy()

In [44]:
df_backup

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [45]:
df_backup['DATA INICIAL'] = pd.to_datetime(df_backup['DATA INICIAL'])

In [46]:
df_backup['DATA FINAL'] = pd.to_datetime(df_backup['DATA FINAL'])

In [49]:
df_backup['DATA FINAL']

0        2004-05-15
1        2004-05-15
2        2004-05-15
3        2004-05-15
4        2004-05-15
            ...
120818   2021-05-01
120819   2021-05-01
120820   2021-05-01
120821   2021-05-01
120822   2021-05-01
Name: DATA FINAL, Length: 120823, dtype: datetime64[ns]

In [50]:
df_backup['DATA INICIAL']

0        2004-05-09
1        2004-05-09
2        2004-05-09
3        2004-05-09
4        2004-05-09
            ...
120818   2021-04-25
120819   2021-04-25
120820   2021-04-25
120821   2021-04-25
120822   2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: datetime64[ns]

In [53]:
type(df_backup['data inicial'.upper()].iloc[2])

pandas._libs.tslibs.timestamps.Timestamp

# 5. Crie uma nova coluna para representar somente o mês e o ano (mm-AAAA), usando a coluna data final como referencia

In [58]:
df_backup['MES_ANO_FINAL'] = df_backup['DATA FINAL'].dt.to_period('M')

In [59]:
df_backup['MES_ANO_FINAL']

0         2004-05
1         2004-05
2         2004-05
3         2004-05
4         2004-05
           ...
120818    2021-05
120819    2021-05
120820    2021-05
120821    2021-05
120822    2021-05
Name: MES_ANO_FINAL, Length: 120823, dtype: period[M]

In [64]:
df_backup['ANO-MES'] = (df_backup['DATA FINAL'].apply(lambda x: "{}".format(x.year)) + df_backup['DATA FINAL'].apply(lambda x: "-{:02d}".format(x.month)))

In [66]:
df_backup['ANO-MES']

0         2004-05
1         2004-05
2         2004-05
3         2004-05
4         2004-05
           ...
120818    2021-05
120819    2021-05
120820    2021-05
120821    2021-05
120822    2021-05
Name: ANO-MES, Length: 120823, dtype: object

# 6. Utilizando o value_counts(), liste todos os tipos de produtos na base de dados

In [68]:
df_backup['produto'.upper()].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

# 7. Filtre o Dataframe para obter apenas dados da GASOLINA COMUm. grave em nova variável.

In [72]:
dados_gasolina = df_backup[df_backup['PRODUTO'] == 'gasolina comum'.upper()] #dataframe onde a coluna x eh maior que zero. ele corta as linhas onde a condicao e falsa

In [73]:
dados_gasolina.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MES_ANO_FINAL,ANO-MES
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.99,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05,2004-05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.85,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05,2004-05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.00,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05,2004-05
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.97,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05,2004-05
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.00,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05,2004-05

In [74]:
dados_gasolina.tail()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MES_ANO_FINAL,ANO-MES
120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,2021-05
120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,2021-05
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,2021-05
120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,2021-05
120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05,2021-05

# 8. Preço médio de revenda da gasolina agosto/2008

In [86]:
ago_2008 = dados_gasolina[dados_gasolina['MES_ANO_FINAL'] == pd.Period('2008-08')]

In [91]:
media_revenda = ago_2008['PREÇO MÉDIO REVENDA'].mean().round(3)
print('O valor médio de revenda da gasolina em 08-2008 eh {}'.format(media_revenda))

O valor médio de revenda da gasolina em 08-2008 eh 2.601

# 9. Preço médio de revenda da gasolina em maio/2014 em São Paulo

In [93]:
maio_2014 = dados_gasolina[dados_gasolina['MES_ANO_FINAL'] == pd.Period('2014-05')]

In [94]:
sao_paulo = maio_2014[maio_2014['ESTADO'] == 'SAO PAULO']

In [95]:
media_sp_052014 = sao_paulo['PREÇO MÉDIO REVENDA'].mean().round(3)
print('O preço médio de revenda da gasolina em 05/2014 em SP é {}'.format(media_sp_052014))

O preço médio de revenda da gasolina em 05/2014 em SP é 2.882

# 10. Quais estados a gasolina ultrapassou 5 reais? Quando isso ocorreu?

In [101]:
maior_que_5_reais = dados_gasolina[dados_gasolina['PREÇO MÉDIO REVENDA'] >= 5][['ESTADO', 'ANO-MES', 'PREÇO MÉDIO REVENDA']]

In [103]:
print('Estados onde a gasolina ultrapassou os 5 reais:\n{}'.format(maior_que_5_reais.value_counts()))

Estados onde a gasolina ultrapassou os 5 reais:
ESTADO          ANO-MES  PREÇO MÉDIO REVENDA
ALAGOAS         2021-04  5.633                  2
CEARA           2021-04  5.503                  2
RIO DE JANEIRO  2020-02  5.025                  2
                2018-06  5.000                  1
                2020-02  5.019                  1
                                               ..
ESPIRITO SANTO  2021-03  5.656                  1
                         5.591                  1
                         5.434                  1
                2021-02  5.172                  1
TOCANTINS       2021-05  5.751                  1
Name: count, Length: 352, dtype: int64

## Crie uma tabela contendo uma serie temporal com a diferença absoluta e percentual entre os valores mais baratos e mais caros. Mostrar os estados onde há os maiores e menores preços

In [104]:
dados_gasolina['DIFF_ABS_MAX_MIN'] = dados_gasolina['PREÇO MÁXIMO REVENDA'] - dados_gasolina['PREÇO MÍNIMO REVENDA']

C:\Users\visitantefacs\AppData\Local\Temp\ipykernel_17296\2701713205.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_gasolina['DIF_ABS_MAX_MIN'] = dados_gasolina['PREÇO MÁXIMO REVENDA'] - dados_gasolina['PREÇO MÍNIMO REVENDA']

In [ ]:
df_max = df2.groupby("ANO-MES").max()["PREÇO MÉDIO REVENDA"].sort_index()
idx_max = df2.groupby('ANO-MES')["PREÇO MÉDIO REVENDA"].idxmin()

df_min = df2.groupby("ANO-MES").min()["PREÇO MÉDIO REVENDA"].sort_index()
idx_min = df2.groupby('ANO-MES')["PREÇO MÉDIO REVENDA"].idxmax()
df_diff = pd.DataFrame()

df_diff["abs_diff"] = df_max - df_min
df_diff["perct_diff"] = (df_max - df_min) / df_min * 100
df_diff["max"] = df_max
df_diff["min"] = df_min

# Print esse codigo abaixo em outra celula. A resposta está aqui.
df2.loc[idx_max, :][["ESTADO", "PREÇO MÉDIO REVENDA", "ANO-MES"]]


df_diff["ESTADO_MAX"] = df2.loc[idx_max, :]["ESTADO"].values
df_diff["ESTADO_MIN"] = df2.loc[idx_min, :]["ESTADO"].values

df_diff["ESTADO_MAX"].value_counts()

df_diff["ESTADO_MIN"].value_counts()